title: Your awesome title
brand: Erol
address: Bogholder Allé 65, 2720 Vanløse
phone: + 40 789 457 689
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-polyglot

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  # - assets/scss



destination: dist
source: src

# Sass
sass:
    sass_dir: assets/css
    style: compressed

# Localization
languages: ["en", "ro"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: false